################################################################################
# 공통 실행 환경
################################################################################
booking:
  version: "0.0.1"
  title: "Booking System"

spring:
  profiles:
    active:
      # 아무것도 지정 하지 않을 경우 기본적으로 local 에서 실행 되도록 한다.
      - local
  main:
    # Boot 2.1 부터 프로젝트 상속 관계인 경우 bean 이 2중 생성되는 문제로 overwrite 옵션을 켜야 한다.
    allow-bean-definition-overriding: true
  ##############################################################################
  # JPA 설정
  ##############################################################################
  booking-jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        # N+1 쿼리 문제를 해결하기 위해 패치 사이즈를 100으로 부여. 부모 1 SQL 후에 자식에 대해서는 in 에  Id 를 100개 가지 넣고 조회
        # N+1 참조 : https://jojoldu.tistory.com/165
        # fetch_size 관련 참조 : https://kihoonkim.github.io/2017/09/09/java/noexception-in-stream-operations/
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul # timezone 설정
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true